AllCops:
  TargetRubyVersion: 2.5
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/AsciiComments:
  Enabled: false
ClassLength:
  Max: 350
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
