sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
  - gem install bundler -v 1.13.0
  - curl https://gist.githubusercontent.com/dtan4/351d031bec0c3d45cd8f/raw/mecab_install.sh | bash
cache: bundler
